### ISSUE TITLE
Error when response is 400

### ISSUE THREAD

**Issue by marco76** [marco76/java-demo#30]
The result on the screen doesn't seem affected but the logs are filled with this exception:

 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-11) RESTEASY002010: Failed to execute: javax.ws.rs.NotAllowedException: RESTEASY003650: No resource method found for GET, return 405 with Allow header
at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:382)
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:121)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
        at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48)
        at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:445)

**Comment by marco76** [comment]
it happens only on systems behind firewall?
